
title: AstroPlant
description: The citizen science space farming kit.
twitter: astroplant
authors: Arn van der Pluijm
social_logo_path: /assets/brand/astroplant-social-logo.png
social_image_path: /assets/brand/astroplant-social.png
